<?php
?>

<!--<div>-->
<!--    #<span class="id">--><?//=$user->getId();?><!--</span><br>-->
<!--    <span class="name">--><?//=$user->getName();?><!--</span><br>-->
<!--</div>-->
<hr><b>Log in</b> if you already have an account
<form action="login" method="post" id="login-form">
    <label for="login">Login:</label>
    <input type="text" id="login" name="login">
    <label for="password">Password:</label>
    <input type="password" id="password" name="password">

<!--    <input type="hidden" id="authorizating" name="authorizating" value="1">-->
<!--    <a id="authorization" class="btn btn-info" href="/login"></a>-->
    <button class="btn btn-info" type="submit">Log in!</button>
</form>

<hr>or <b>sign up</b> - confirm your password and press the button!
<form action="signup" method="post" id="login-form">
    <label for="email">Password (retype):</label>
    <input type="email" id="email" name="email">
    <label for="password">Password:</label>
    <input type="password" id="password" name="password">
    <label for="password2">Password (retype):</label>
    <input type="password" id="password2" name="password2">
    <label for="name">Login:</label>
    <input type="text" id="name" name="name">

<!--    <input type="hidden" id="authorizating" name="authorizating" value="1">-->
<!--    <a id="registration" class="btn btn-info" href="/signup">Log in!</a>-->
    <button class="btn btn-info" type="submit">Sign up!</button>
</form>
