<hr><form action="/file/file/gallery" method="post" id="user-gallery-form">
    <button class="btn btn-info" type="submit">Show user's photos!</button>
</form>

<hr><form action="/user/user/list" method="post" id="user-list-form">
    <button class="btn btn-info" type="submit">Get user list!</button><br>
    <label>
        <input name="sort" type="radio" value="ASC" checked>
        <div>ASC</div>
    </label>
    <label>
        <input name="sort" type="radio" value="DESC">
        <div>DESC</div>
    </label>
</form>

<hr><form enctype="multipart/form-data" action="/file/file/upload" method="post" id="upload-form">
    <label for="photo">Upload photo:</label>
    <input type="file" id="photo" name="photo">
    <button class="btn btn-info" type="submit">Upload!</button>
</form>

<hr><form action="/file/file/modify" method="post" id="modify-form">
    <button class="btn btn-info" type="submit">Modify photo on server!</button>
</form>

<hr>ADMIN CONTROLS - edit or create user<hr>
<form enctype="multipart/form-data" action="/user/user/admin" method="post" id="admin-form">
    <label for="email">Email:</label>
    <input type="email" id="email" name="email">
    <label for="password">Password:</label>
    <input type="password" id="password" name="password">
    <label for="password2">Password (retype):</label>
    <input type="password" id="password2" name="password2">
    <label for="name">Name:</label>
    <input type="text" id="name" name="name">
    <label for="age">Age:</label>
    <input type="number" id="age" name="age">
    <label for="avatar">Avatar:</label>
    <input type="file" id="avatar" name="avatar">

    <input type="submit" value="Create user" name="create" />
    <input type="submit" value="Edit user" name="edit" />
</form>
